# Generated by Django 5.0.6 on 2024-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='Processor',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
