# Generated by Django 5.0.6 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_attribute_attribute_name_attribute_processor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='Processor',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
