# Generated by Django 5.0.6 on 2024-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_costumers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumers',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='costumers',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(related_name='attributes', to='blog.attribute'),
        ),
    ]
