# Generated by Django 5.0.6 on 2024-06-06 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_customers_delete_costumers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
