# Generated by Django 5.0.6 on 2024-06-06 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_customers_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
