# Generated by Django 5.0.6 on 2024-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_customers_image_alter_customers_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='first_name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='last_name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
